name: NegativeStain
atlas:
  acquisition:
      - setAtlasOptics 
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  acquisition:
    - moveStage
    - realignToSquare
    - eucentricity
    - square
  targets:
    finders:
      - Regular pattern
    selectors:
      - Graylevel selector
mediumMag:
  acquisition:
    - moveStage
    - mediumMagHole
highMag:
  acquisition:
    - highMag
