name: Test Call
atlas:
  acquisition:
      - setAtlasOptics
      - resetStage
      - removeSlit
      - callFuntion:
          function: mockScript::MyFunction
          args:
            - 1
            - 2
            - 3
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  acquisition:
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - call:
        script: Z_byV
    - square
  targets:
    finders:
      - AI hole finder
      - Regular pattern
    selectors:
      - Graylevel selector
mediumMag:
  acquisition:
    - setFocusPosition
    - tiltToAngle
    - moveStage
    - loadHoleRef
    - alignToHoleRef
    - mediumMagHole
highMag:
  acquisition:
    - highMag
