version: "3"
services:
  smartscope:
    image: localhost/smartscope:0.62
    container_name: smartscope
    build:
      context: .
      args:
        - USER_ID=1001 #Set a specific user ID for the smartscope_user account in the container. Useful to match existing host id
        - GROUP_ID=20800 #Set a specific group ID for the smartscope_group account in the container. Useful to match existing host id
    restart: always
    volumes:
      #Volumes are spelled /path/on/host/:/path/in/container/
      - /datastaging/data/smartscope/:/mnt/data/ #Where the data is to be saved (required)
      - /auto_screening/log_dev/:/opt/logs/ #Where the log files are to be saved (required)
      - /home/bouvettej2/Smartscope-dev/:/opt/smartscope/ #Path to the Repo. It's technically already in the container. Useful for development/troubleshooting
      - /ddn/cryoemCore/data/auto_screening/:/mnt/longterm/ #Use if USE_LONGTERMSTORAGE: True
      - /auto_screening/tmp/scope/smartscope_testfiles/:/mnt/testfiles/ #Use to mount test files directory for testing
      ### Microscopes ### One mount per microscope to /mnt/{micoscope_name}/
      - /mnt/gatan_Raid_X:/mnt/arctica/
      - /mnt/krios_Raid_X:/mnt/krios/
      - /auto_screening/tmp/scope/:/mnt/fake_scope/
      - /home/bouvettej2/Template_files/:/opt/Template_files/
      ### Extra locations ###
      - /datastaging/data/gatan_movies/:/mnt/preprocess/
    environment:
      ALLOWED_HOSTS: localhost,lxd-02012614,192.168.0.198 #List of allowed hostnames for connection, comma separated without spaces
      USE_STORAGE: 'True' #Usually set to True, can be turned off for a server that would only read from long-term storage. Need to have a volume mounted to /mnt/data/
      USE_LONGTERMSTORAGE: 'True' #True if the data gets transfered and read from another storage areas. Shoud have volume mounted to /mnt/longterm 
      LOGLEVEL: DEBUG #Log level, choices are INFO, WARNING, CRITICAL, DEBUG. default:INFO
      DEBUG: 'True' #set to True to get a django debug page whenever a page isn't found or an error occurs while loading assets to the web browser.
      SECRET_KEY: 'd41d8cd98f00b204e9800998eag' #Make sure this is unique! Generate a new one with: $RANDOM | md5sum | head -c 25
    depends_on:
      - db
      - cache
    networks:
      - smartscopenet
    command: gunicorn -c /opt/smartscope/config/docker/gunicorn.conf.py
    deploy:
      #Used to pass the GPU through. Also need to install the nvidia-container-toolkit.
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  db:
    image: mariadb:10.5
    container_name: smartscope-db
    restart: always
    ports:
      - 6603:3306
    volumes:
      - /auto_screening/tmp/test_db3/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: smartscope #Name of the database to use. Will be created automatically if doesn't exist
      MYSQL_USER: root #Username to use for database connection. Currently needs to be root (needs to be changed)
      MYSQL_PASSWORD: #Not used
      MYSQL_ROOT_PASSWORD: pass #Set a password for the root user
    networks:
      - smartscopenet
  cache:
    image: redis:6.2-alpine
    restart: always
    # ports:
    #   - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - smartscopenet
  nginx:
    image: nginx
    ports:
      - 58000:80 #Bind a different port on host by changing the first value. i.e. 8080:80.
      # - 443:443 #Use if you choose to use ssl. RECOMMENDED
    volumes:
      - ./config/docker/templates_noSSL/:/etc/nginx/templates/ #Change to ./config/docker/templates_SSL to use SSL
      #- /path/to/certs/cert.pem:/opt/certs/smartscope.crt #Uncomment to mount the ssl certificate from the host
      #- /path/to/certs/privkey.pem:/opt/certs/smartscope.key #Uncomment to mount the ssl certificate from the host
      - /datastaging/data/smartscope/:/mnt/data/ #Where the data is to be saved (required)
      - /auto_screening/log_dev:/opt/logs/ #Where the log files are to be saved (required)
      - /home/bouvettej2/Smartscope-dev/static/:/opt/smartscope/static/ #Path to the Repo static files. It's technically for the javascript assets
      - /ddn/cryoemCore/data/auto_screening/:/mnt/longterm/ #Use if USE_LONGTERMSTORAGE: True
    environment:
      SERVER_NAME: lxd-02012614 #Should match the ALLOWED_HOSTS from the smartscope service
    networks:
      - smartscopenet
    depends_on:
      - smartscope

networks:
  smartscopenet: {}
