########################################################################
# For details about the docker-compose file, please refer to           #
# https://docs.smartscope.org/installation/docker-compose_details.html #
########################################################################
version: "3"
services:
  smartscope:
    image: localhost/smartscope:0.8b3
    container_name: smartscope
    build:
      context: .
    restart: always
    volumes:
      ######## FILL THIS ##########
      - :/mnt/data/
      ######## ADD YOUR MICROSCOPES #########
      # The synthax from the microscope volumes is as follows:
      # - /path/to/where/serialem/will/write/files/:/mnt/your_scope_name_here/
      # Example:
      # - /mnt/gatan_Raid_X/smartscope/:/mnt/arctica/
    environment:
      SECRET_KEY: 'd41d8cd98f00b204e9800998eag' #Make sure this is unique! Generate a new one with: $RANDOM | md5sum | head -c 25
    depends_on:
      - db
      - cache
    networks:
      - smartscopenet
  db:
    image: mariadb:10.5
    container_name: smartscope-db
    restart: always
    volumes:
      ######## FILL ONLY THE FIRST VALUE ##########
      - :/var/lib/mysql
      - ./config/docker/initialdb.sql:/docker-entrypoint-initdb.d/initialdb.sql ##Copies the initial db file to initialize the datase on first launch##
    environment:
      MYSQL_DATABASE: smartscope
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - smartscopenet
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - smartscopenet
  nginx:
    image: nginx
    ports:
      - 48000:80
    volumes:
      - ./static/:/opt/smartscope/static/ #Doesn't need to be changed
      - ./config/docker/templates_noSSL/:/etc/nginx/templates/ #Change if using SSL, view docs for more info.
    networks:
      - smartscopenet
    depends_on:
      - smartscope

networks:
  smartscopenet: {}
