########################################################################
# For details about the docker-compose file, please refer to           #
# https://docs.smartscope.org/installation/docker-compose_details.html #
########################################################################
version: "3"
services:
  smartscope:
    image: localhost/smartscope:0.62
    container_name: smartscope
    build:
      context: .
    restart: always
    volumes:
      ######## FILL THIS ##########
      - :/mnt/data/
      - :/opt/Template_files/
    environment:
      SECRET_KEY: 'd41d8cd98f00b204e9800998eag' #Make sure this is unique! Generate a new one with: $RANDOM | md5sum | head -c 25
    depends_on:
      - db
      - cache
    networks:
      - smartscopenet
  db:
    image: mariadb:10.5
    container_name: smartscope-db
    restart: always
    ports:
      - 6603:3306
    volumes:
      ######## FILL THIS ##########
      - :/var/lib/mysql
    environment:
      MYSQL_DATABASE: smartscope
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
    networks:
      - smartscopenet
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - smartscopenet
  nginx:
    image: nginx
    ports:
      - 48000:80
    volumes:
      ######## FILL ONLY THE FIRST VALUE ##########
      - :/mnt/data/
      - ./static/:/opt/smartscope/static/
      - ./config/docker/templates_noSSL/:/etc/nginx/templates/
    networks:
      - smartscopenet
    depends_on:
      - smartscope

networks:
  smartscopenet: {}
