########################################################################
# For details about the docker-compose file, please refer to           #
# https://docs.smartscope.org/installation/docker-compose_details.html #
########################################################################
version: "3"
services:
  smartscope:
    image: ghcr.io/niehs/smartscope:0.8-rc.2
    container_name: smartscope
    restart: always
    volumes:
      ######## FILL THIS ##########
      # - :/mnt/data/
      ######## ADD YOUR MICROSCOPES #########
      # The synthax from the microscope volumes is as follows:
      # - /path/to/where/serialem/will/write/files/:/mnt/your_scope_name_here/
      # Example:
      # - /mnt/gatan_Raid_X/smartscope/:/mnt/arctica/
      ###### OTHER DEFAULT VOLUMES - NO NEED TO CHANGE ####### 
      - shared-config:/opt/shared/:rw
      - config:/opt/config/:rw
    env_file:
      - /opt/smartscope/docker/default.env
      - /opt/shared/custom.env
    depends_on:
      - db
      - cache
    networks:
      - smartscopenet
  db:
    image: mariadb:10.5
    container_name: smartscope-db
    restart: always
    environment:
      MYSQL_DATABASE: smartscope
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - shared-config:/opt/shared/:ro
      - smartscope-db:/var/lib/mysql/
    networks:
      - smartscopenet
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - smartscopenet
  nginx:
    image: nginx
    ports:
      - 48000:80
    volumes:
      - shared-config:/opt/shared/:ro #Doesn't need to be changed
    networks:
      - smartscopenet
    depends_on:
      - smartscope
    command: /opt/shared/nginx-entrypoint.sh
    
networks:
  smartscopenet: {}

volumes:
  shared-config:
  config:
  smartscope-db:
