# Generated by Django 4.2.2 on 2024-01-03 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def populate_new_field(apps, schema_editor):
    model = apps.get_model('API', 'holetype')
    for instance in model.objects.all():
        print(instance)
        # Perform the necessary operations to set the new field
        instance.holetype_id = instance.name.replace('/', '_').replace(' ', '_').replace('.','').lower()
        instance.save()

def populate_new_fk(apps, schema_editor):
    holetype_model = apps.get_model('API', 'holetype')
    model = apps.get_model('API', 'autoloadergrid')
    for instance in model.objects.all():
        print(instance)
        # Perform the necessary operations to set the new field
        instance.holetype_id = holetype_model.objects.get(name=instance.holeType)
        instance.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0017_alter_customgrouppath_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningsession',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='holetype',
            name='holetype_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(populate_new_field),
        migrations.RunPython(populate_new_fk),
            migrations.RemoveField(
            model_name='autoloadergrid',
            name='holeType',
        ),
        migrations.AlterField(
            model_name='holetype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='holetype',
            name='holetype_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='autoloadergrid',
            name='holetype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.holetype'),
        ),
        migrations.AlterField(
            model_name='holetype',
            name='holetype_id',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='holetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        # migrations.AlterField(
        #     model_name='holetype',
        #     name='name',
        #     field=models.CharField(max_length=30, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='holetype',
        #     name='holetype_id',
        #     field=models.CharField(max_length=30, primary_key=True, serialize=False),
        # ),
        # migrations.AddField(
        #     model_name='autoloadergrid',
        #     name='holetype_id',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holetype_id_fk', to='API.holetype', to_field='holetype_id'),
        # ),


        # migrations.RunPython(populate_new_fk),

    ]
