##Use this file to design rules for how to automatically set default protocol for a grid.
- conditions:
    - [holetype_id.name, NegativeStain]
    - [holetype_id.name, Lacey]
    - [holetype_id.name, MultiA]
  mode: any
  protocol: NegativeStain
- conditions:
    - [params_id.bis_max_distance, 0]
    - [params_id.tilt_angle, '!__0']
  mode: any
  protocol: SPA
- conditions:
    - [holetype_id.hole_size, '!__None']
    - [params_id.bis_max_distance, '!__0']
    - [params_id.tilt_angle, 0]
  mode: all
  protocol: SPA-Ptolemy