SPA:
    squareFinders:
        - AI square finder
        # - Square finder
    holeFinders:
        - AI hole finder
        # - Binary finder
        - Regular pattern
    squareSelectors:
        - Size selector
    holeSelectors:
        - Graylevel selector

NegativeStain:
    squareFinders:
        - AI square finder
        - Square finder
    holeFinders:
        - Regular pattern
    squareSelectors:
        - Size selector
    holeSelectors:
        - Graylevel selector